# Generated by Django 3.2.9 on 2021-11-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
