# Generated by Django 3.2.9 on 2021-11-22 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211121_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
