# Generated by Django 3.2.9 on 2021-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_uploads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
